<?php

namespace Database\Seeders;

use App\Models\ConditionerType;
use Illuminate\Database\Seeder;

class ConditionerTypeSeeder extends Seeder
{
    public function run(): void
    {
        $conditionerTypes = [
            [
                'name' => 'AIRWAYHeatpumpIR',
                'device' => 'touchon-ir-ac',
                'temperature' => '{"min":18,"max":30}',
                'mode' => '{"auto":1,"heat":2,"cool":3,"dry":4,"fan":5}',
                'fan' => '{"auto":0,"1":1,"2":2,"3":3}',
                'vdir' => '{"auto":0,"swing":1,"up":2,"mup":3,"middle":4,"mdown":5,"down":6}',
                'hdir' => null,
            ],
            [
                'name' => 'AUXHeatpumpIR',
                'device' => 'touchon-ir-ac',
                'temperature' => '{"min":16,"max":30}',
                'mode' => '{"auto":1,"heat":2,"cool":3,"dry":4,"fan":5}',
                'fan' => '{"auto":0,"1":1,"2":2,"3":3}',
                'vdir' => '{"manual":0,"swing":1}',
                'hdir' => '{"manual":0,"swing":1}',
            ],
            [
                'name' => 'BalluHeatpumpIR',
                'device' => 'touchon-ir-ac',
                'temperature' => '{"min":16,"max":30}',
                'mode' => '{"auto":1,"heat":2,"cool":3,"dry":4,"fan":5}',
                'fan' => '{"auto":0,"1":1,"2":2,"3":3}',
                'vdir' => null,
                'hdir' => null,
            ],
            [
                'name' => 'BGHHeatpumpIR',
                'device' => 'touchon-ir-ac',
                'temperature' => '{"min":18,"max":32}',
                'mode' => '{"auto":1,"heat":2,"cool":3,"dry":4,"fan":5,"maint":6}',
                'fan' => '{"1":3,"2":2,"3":1}',
                'vdir' => null,
                'hdir' => null,
            ],
            [
                'name' => 'CarrierHeatpumpIR_MCA',
                'device' => 'touchon-ir-ac',
                'temperature' => '{"min":17,"max":30}',
                'mode' => '{"auto":1,"heat":2,"cool":3,"dry":4,"fan":5}',
                'fan' => '{"auto":0,"1":1,"2":2,"3":3}',
                'vdir' => null,
                'hdir' => null,
            ],
            [
                'name' => 'CarrierHeatpumpIR_NQV',
                'device' => 'touchon-ir-ac',
                'temperature' => '{"min":17,"max":30}',
                'mode' => '{"auto":1,"heat":2,"cool":3,"dry":4,"fan":5}',
                'fan' => '{"auto":0,"1":1,"2":2,"3":3,"4":4}',
                'vdir' => null,
                'hdir' => null,
            ],
            [
                'name' => 'DaikinHeatpumpARC417IR',
                'device' => 'touchon-ir-ac',
                'temperature' => '{"min":18,"max":28}',
                'mode' => '{"auto":1,"heat":2,"cool":3,"dry":4,"fan":5}',
                'fan' => '{"auto":0,"1":1,"2":2,"3":3,"4":4,"5":5}',
                'vdir' => null,
                'hdir' => null,
            ],
            [
                'name' => 'DaikinHeatpumpARC480A14IR',
                'device' => 'touchon-ir-ac',
                'temperature' => '{"min":18,"max":30}',
                'mode' => '{"auto":1,"heat":2,"cool":3,"dry":4,"fan":5}',
                'fan' => '{"auto":0,"1":1,"2":2,"3":3,"4":4,"5":5,"silent":6}',
                'vdir' => '{"swing":1,"up":2}',
                'hdir' => null,
            ],
            [
                'name' => 'DaikinHeatpumpIR',
                'device' => 'touchon-ir-ac',
                'temperature' => '{"min":18,"max":30}',
                'mode' => '{"auto":1,"heat":2,"cool":3,"dry":4,"fan":5}',
                'fan' => '{"auto":0,"1":1,"2":2,"3":3,"4":4,"5":5}',
                'vdir' => null,
                'hdir' => null,
            ],
            [
                'name' => 'ElectroluxYALHeatpumpIR',
                'device' => 'touchon-ir-ac',
                'temperature' => '{"min":16,"max":30}',
                'mode' => '{"auto":1,"heat":2,"cool":3,"dry":4,"fan":5}',
                'fan' => '{"auto":0,"1":1,"2":2,"3":3}',
                'vdir' => '{"auto":0,"swing":1}',
                'hdir' => '{"auto":0,"swing":1}',
            ],
            [
                'name' => 'FuegoHeatpumpIR',
                'device' => 'touchon-ir-ac',
                'temperature' => '{"min":18,"max":31}',
                'mode' => '{"auto":1,"heat":2,"cool":3,"dry":4,"fan":5}',
                'fan' => '{"auto":0,"1":1,"2":2,"3":3}',
                'vdir' => '{"auto":0,"swing":1,"up":2,"mup":3,"middle":4,"mdown":5,"down":6}',
                'hdir' => null,
            ],
            [
                'name' => 'FujitsuHeatpumpIR',
                'device' => 'touchon-ir-ac',
                'temperature' => '{"min":16,"max":30}',
                'mode' => '{"auto":1,"heat":2,"cool":3,"dry":4,"fan":5}',
                'fan' => '{"auto":0,"1":1,"2":2,"3":3,"4":4}',
                'vdir' => '{"manual":0,"swing":1}',
                'hdir' => '{"manual":0,"swing":1}',
            ],
            [
                'name' => 'GreeGenericHeatpumpIR',
                'device' => 'touchon-ir-ac',
                'temperature' => '{"min":16,"max":30}',
                'mode' => '{"auto":1,"heat":2,"cool":3,"dry":4,"fan":5}',
                'fan' => '{"auto":0,"1":1,"2":2,"3":3}',
                'vdir' => '{"auto":0,"swing":1,"up":2,"mup":3,"middle":4,"mdown":5,"down":6}',
                'hdir' => '{"auto":0,"swing":1,"left":3,"mleft":4,"middle":2,"mright":5,"right":6}',
            ],
            [
                'name' => 'HisenseHeatpumpIR',
                'device' => 'touchon-ir-ac',
                'temperature' => '{"min":18,"max":32}',
                'mode' => '{"auto":1,"heat":2,"cool":3,"dry":4,"fan":5,"maint":6}',
                'fan' => '{"auto":0,"1":1,"2":2,"3":3,"4":4,"5":5}',
                'vdir' => '{"auto":0,"swing":1,"up":2,"mup":3,"middle":4,"mdown":5,"down":6}',
                'hdir' => '{"auto":0,"swing":1,"left":3,"mleft":4,"middle":2,"mright":5,"right":6}',
            ],
            [
                'name' => 'HitachiHeatpumpIR',
                'device' => 'touchon-ir-ac',
                'temperature' => '{"min":16,"max":32}',
                'mode' => '{"auto":1,"heat":2,"cool":3,"dry":4,"fan":5}',
                'fan' => '{"auto":0,"1":1,"2":2,"3":3,"4":4}',
                'vdir' => '{"auto":0,"swing":1}',
                'hdir' => '{"auto":0,"swing":1}',
            ],
            [
                'name' => 'HyundaiHeatpumpIR',
                'device' => 'touchon-ir-ac',
                'temperature' => '{"min":16,"max":30}',
                'mode' => '{"auto":1,"heat":2,"cool":3,"dry":4,"fan":5}',
                'fan' => '{"auto":0,"1":1,"2":2,"3":3}',
                'vdir' => '{"auto":0,"swing":1}',
                'hdir' => null,
            ],
            [
                'name' => 'IVTHeatpumpIR',
                'device' => 'touchon-ir-ac',
                'temperature' => '{"min":17,"max":31}',
                'mode' => '{"heat":2,"cool":3,"dry":4}',
                'fan' => '{"auto":0,"1":1,"2":2,"3":3}',
                'vdir' => null,
                'hdir' => null,
            ],
            [
                'name' => 'MideaHeatpumpIR',
                'device' => 'touchon-ir-ac',
                'temperature' => '{"min":17,"max":30}',
                'mode' => '{"auto":1,"heat":2,"cool":3,"dry":4,"fan":5,"maint":6}',
                'fan' => '{"auto":0,"1":1,"2":2,"3":3}',
                'vdir' => null,
                'hdir' => null,
            ],
            [
                'name' => 'MitsubishiFDHeatpumpIR',
                'device' => 'touchon-ir-ac',
                'temperature' => '{"min":17,"max":31}',
                'mode' => '{"auto":1,"heat":2,"cool":3,"dry":4,"fan":5}',
                'fan' => '{"auto":0,"1":1,"2":2,"3":3,"4":4,"5":5}',
                'vdir' => '{"auto":0,"swing":1,"up":2,"mup":3,"middle":4,"mdown":5,"down":6}',
                'hdir' => '{"auto":0,"swing":1,"left":3,"mleft":4,"middle":2,"mright":5,"right":6}',
            ],
            [
                'name' => 'MitsubishiHeavyFDTCHeatpumpIR',
                'device' => 'touchon-ir-ac',
                'temperature' => '{"min":18,"max":30}',
                'mode' => '{"auto":1,"heat":2,"cool":3,"dry":4,"fan":5}',
                'fan' => '{"1":1,"2":2,"3":3}',
                'vdir' => '{"swing":1,"up":2,"mup":3,"mdown":5,"down":6}',
                'hdir' => null,
            ],
            [
                'name' => 'MitsubishiHeavyZJHeatpumpIR',
                'device' => 'touchon-ir-ac',
                'temperature' => '{"min":18,"max":30}',
                'mode' => '{"auto":1,"heat":2,"cool":3,"dry":4,"fan":5}',
                'fan' => '{"auto":0,"1":1,"2":2,"3":3}',
                'vdir' => '{"swing":1,"up":2,"mup":3,"middle":4,"mdown":5,"down":6}',
                'hdir' => '{"swing":1,"left":3,"mleft":4,"middle":2,"mright":5,"right":6}',
            ],
            [
                'name' => 'MitsubishiHeavyZMHeatpumpIR',
                'device' => 'touchon-ir-ac',
                'temperature' => '{"min":18,"max":30}',
                'mode' => '{"auto":1,"heat":2,"cool":3,"dry":4,"fan":5,"maint":6}',
                'fan' => '{"auto":0,"1":1,"2":2,"3":3,"4":4}',
                'vdir' => '{"swing":1,"up":2,"mup":3,"middle":4,"mdown":5,"down":6}',
                'hdir' => '{"swing":1,"left":3,"mleft":4,"middle":2,"mright":5,"right":6}',
            ],
            [
                'name' => 'MitsubishiHeavyZMPHeatpumpIR',
                'device' => 'touchon-ir-ac',
                'temperature' => '{"min":18,"max":30}',
                'mode' => '{"auto":1,"heat":2,"cool":3,"dry":4,"fan":5,"maint":6}',
                'fan' => '{"auto":0,"1":1,"2":2,"3":3}',
                'vdir' => '{"swing":1,"up":2,"mup":3,"middle":4,"mdown":5,"down":6}',
                'hdir' => null,
            ],
            [
                'name' => 'MitsubishiMSCHeatpumpIR',
                'device' => 'touchon-ir-ac',
                'temperature' => '{"min":16,"max":31}',
                'mode' => '{"auto":1,"heat":2,"cool":3,"dry":4,"fan":5}',
                'fan' => '{"auto":0,"1":1,"2":2,"3":3}',
                'vdir' => '{"auto":0,"swing":1,"up":2,"mup":3,"middle":4,"mdown":5,"down":6}',
                'hdir' => null,
            ],
            [
                'name' => 'MitsubishiSEZKDXXHeatpumpIR',
                'device' => 'touchon-ir-ac',
                'temperature' => '{"min":17,"max":30}',
                'mode' => '{"auto":1,"heat":2,"cool":3,"dry":4,"fan":5}',
                'fan' => '{"1":1,"2":2,"3":3}',
                'vdir' => null,
                'hdir' => null,
            ],
            [
                'name' => 'NibeHeatpumpIR',
                'device' => 'touchon-ir-ac',
                'temperature' => '{"min":16,"max":32}',
                'mode' => '{"auto":1,"heat":2,"cool":3,"dry":4,"fan":5}',
                'fan' => '{"auto":0,"1":1,"2":2,"3":3}',
                'vdir' => '{"auto":0,"swing":1,"up":2,"mup":3,"middle":4,"mdown":5,"down":6}',
                'hdir' => null,
            ],
            [
                'name' => 'PanasonicAltDKEHeatpumpIR',
                'device' => 'touchon-ir-ac',
                'temperature' => '{"min":16,"max":30}',
                'mode' => '{"auto":1,"heat":2,"cool":3,"dry":4,"fan":5}',
                'fan' => '{"auto":0,"1":1,"2":2,"3":3,"4":4,"5":5}',
                'vdir' => '{"auto":0,"swing":1,"up":2,"mup":3,"middle":4,"mdown":5,"down":6}',
                'hdir' => '{"auto":0,"swing":1,"left":3,"mleft":4,"middle":2,"mright":5,"right":6}',
            ],
            [
                'name' => 'PanasonicDKEHeatpumpIR',
                'device' => 'touchon-ir-ac',
                'temperature' => '{"min":16,"max":30}',
                'mode' => '{"auto":1,"heat":2,"cool":3,"dry":4,"fan":5}',
                'fan' => '{"auto":0,"1":1,"2":2,"3":3,"4":4,"5":5}',
                'vdir' => '{"auto":0,"swing":1,"up":2,"mup":3,"middle":4,"mdown":5,"down":6}',
                'hdir' => '{"auto":0,"swing":1,"left":3,"mleft":4,"middle":2,"mright":5,"right":6}',
            ],
            [
                'name' => 'PanasonicJKEHeatpumpIR',
                'device' => 'touchon-ir-ac',
                'temperature' => '{"min":16,"max":30}',
                'mode' => '{"auto":1,"heat":2,"cool":3,"dry":4,"fan":5}',
                'fan' => '{"auto":0,"1":1,"2":2,"3":3,"4":4,"5":5}',
                'vdir' => '{"auto":0,"swing":1,"up":2,"mup":3,"middle":4,"mdown":5,"down":6}',
                'hdir' => '{"auto":0,"swing":1,"left":3,"mleft":4,"middle":2,"mright":5,"right":6}',
            ],
            [
                'name' => 'PanasonicNKEHeatpumpIR',
                'device' => 'touchon-ir-ac',
                'temperature' => '{"min":16,"max":30}',
                'mode' => '{"auto":1,"heat":2,"cool":3,"dry":4,"fan":5}',
                'fan' => '{"auto":0,"1":1,"2":2,"3":3,"4":4,"5":5}',
                'vdir' => '{"auto":0,"swing":1,"up":2,"mup":3,"middle":4,"mdown":5,"down":6}',
                'hdir' => '{"auto":0,"swing":1,"left":3,"mleft":4,"middle":2,"mright":5,"right":6}',
            ],
            [
                'name' => 'R51MHeatpumpIR',
                'device' => 'touchon-ir-ac',
                'temperature' => '{"min":17,"max":30}',
                'mode' => '{"auto":1,"heat":2,"cool":3,"dry":4,"fan":5}',
                'fan' => '{"auto":0,"1":1,"2":2,"3":3}',
                'vdir' => null,
                'hdir' => null,
            ],
            [
                'name' => 'SamsungAQV12MSANHeatpumpIR',
                'device' => 'touchon-ir-ac',
                'temperature' => '{"min":16,"max":27}',
                'mode' => '{"auto":1,"heat":2,"cool":3,"dry":4,"fan":5}',
                'fan' => '{"auto":0,"1":1,"2":2,"3":3}',
                'vdir' => '{"auto":0,"swing":1}',
                'hdir' => null,
            ],
            [
                'name' => 'SamsungAQVHeatpumpIR',
                'device' => 'touchon-ir-ac',
                'temperature' => '{"min":16,"max":27}',
                'mode' => '{"auto":1,"heat":2,"cool":3,"dry":4,"fan":5}',
                'fan' => '{"auto":0,"1":1,"2":2,"3":3}',
                'vdir' => '{"auto":0,"swing":1}',
                'hdir' => null,
            ],
            [
                'name' => 'SamsungFJMHeatpumpIR',
                'device' => 'touchon-ir-ac',
                'temperature' => '{"min":16,"max":27}',
                'mode' => '{"auto":1,"heat":2,"cool":3,"dry":4,"fan":5}',
                'fan' => '{"auto":0,"1":1,"2":2,"3":3}',
                'vdir' => '{"auto":0,"swing":1}',
                'hdir' => null,
            ],
            [
                'name' => 'SharpHeatpumpIR',
                'device' => 'touchon-ir-ac',
                'temperature' => '{"min":17,"max":31}',
                'mode' => '{"auto":1,"heat":2,"cool":3,"dry":4,"fan":5}',
                'fan' => '{"auto":0,"1":1,"2":2,"3":3}',
                'vdir' => null,
                'hdir' => null,
            ],
            [
                'name' => 'ToshibaDaiseikaiHeatpumpIR',
                'device' => 'touchon-ir-ac',
                'temperature' => '{"min":17,"max":30}',
                'mode' => '{"auto":1,"heat":2,"cool":3,"dry":4,"fan":5}',
                'fan' => '{"auto":0,"1":1,"2":2,"3":3,"4":4,"5":5}',
                'vdir' => null,
                'hdir' => null,
            ],
            [
                'name' => 'ToshibaHeatpumpIR',
                'device' => 'touchon-ir-ac',
                'temperature' => '{"min":17,"max":30}',
                'mode' => '{"auto":1,"heat":2,"cool":3,"dry":4,"fan":5}',
                'fan' => '{"auto":0,"1":1,"2":2,"3":3,"4":4,"5":5}',
                'vdir' => null,
                'hdir' => null,
            ],
            [
                'name' => 'VaillantHeatpumpIR',
                'device' => 'touchon-ir-ac',
                'temperature' => '{"min":16,"max":30}',
                'mode' => '{"auto":1,"heat":2,"cool":3,"dry":4,"fan":5}',
                'fan' => '{"auto":0,"1":1,"2":2,"3":3}',
                'vdir' => '{"auto":0,"swing":1,"up":2,"mup":3,"middle":4,"mdown":5,"down":6}',
                'hdir' => null,
            ],
            [
                'name' => 'ZHJG01HeatpumpIR',
                'device' => 'touchon-ir-ac',
                'temperature' => '{"min":17,"max":32}',
                'mode' => '{"auto":1,"heat":2,"cool":3,"dry":4,"fan":5}',
                'fan' => '{"auto":0,"1":1,"2":2,"3":3}',
                'vdir' => '{"auto":0,"swing":1}',
                'hdir' => null,
            ],
            [
                'name' => 'ZHLT01HeatpumpIR',
                'device' => 'touchon-ir-ac',
                'temperature' => '{"min":16,"max":32}',
                'mode' => '{"auto":1,"heat":2,"cool":3,"dry":4,"fan":5}',
                'fan' => '{"auto":0,"1":1,"2":2,"3":3,"4":4,"5":5,"silent":6}',
                'vdir' => '{"auto":0,"swing":1}',
                'hdir' => '{"swing":1}',
            ],
            [
                'name' => 'gr-1-mb-b',
                'device' => 'onokom-gr-1-mb-b',
                'temperature' => '{"min":16,"max":30}',
                'mode' => '{"heat":1,"cool":2,"auto":3,"dry":4,"fan":5}',
                'fan' => '{"auto":0,"silent":1,"1":2,"2":3,"3":4,"turbo":5}',
                'vdir' => '{"swing":1,"down":2,"mdown":3,"middle":4,"mup":5,"up":6}',
                'hdir' => '{"swing":1,"left":2,"mleft":3,"middle":4,"mright":5,"right":6}',
            ],
            [
                'name' => 'gr-3-mb-b',
                'device' => 'onokom-gr-3-mb-b',
                'temperature' => '{"min":16,"max":32}',
                'mode' => '{"heat":1,"cool":2,"auto":3,"dry":4,"fan":5}',
                'fan' => '{"auto":0,"silent":1,"1":2,"2":3,"3":4,"4":5,"5":6,"turbo":7}',
                'vdir' => '{"swing":1,"down":2,"mdown":3,"middle":4,"mup":5,"up":6}',
                'hdir' => '{"swing":1,"left":2,"mleft":3,"middle":4,"mright":5,"right":6}',
            ],
            [
                'name' => 'tcl-1-mb-b',
                'device' => 'onokom-tcl-1-mb-b',
                'temperature' => '{"min":16,"max":31}',
                'mode' => '{"heat":1,"cool":2,"auto":3,"dry":4,"fan":5}',
                'fan' => '{"auto":0,"silent":1,"1":2,"2":3,"3":4,"4":5,"5":6,"turbo":7}',
                'vdir' => '{"swing":1,"down":2,"mdown":3,"middle":4,"mup":5,"up":6}',
                'hdir' => '{"swing":1,"left":2,"mleft":3,"middle":4,"mright":5,"right":6,"soft":7}',
            ],
            [
                'name' => 'dk-1-mb-b',
                'device' => 'onokom-dk-1-mb-b',
                'temperature' => '{"min":18,"max":30}',
                'mode' => '{"heat":1,"cool":2,"auto":3,"dry":4,"fan":5}',
                'fan' => '{"auto":0,"silent":1,"1":2,"2":3,"3":4,"4":5,"5":6,"turbo":7}',
                'vdir' => '{"stop":0,"swing":1}',
                'hdir' => '{"stop":0,"swing":1}',
            ],
            [
                'name' => 'aux-1-mb-b',
                'device' => 'onokom-aux-1-mb-b',
                'temperature' => '{"min":18,"max":30}',
                'mode' => '{"heat":1,"cool":2,"auto":3,"dry":4,"fan":5}',
                'fan' => '{"auto":0,"silent":1,"1":2,"2":3,"3":4,"4":5,"5":6,"turbo":7}',
                'vdir' => '{"swing":1,"down":2,"mdown":3,"middle":4,"mup":5,"up":6}',
                'hdir' => '{"stop":0,"swing":1}',
            ],
            [
                'name' => 'me-1-mb-b',
                'device' => 'onokom-me-1-mb-b',
                'temperature' => '{"min":18,"max":30}',
                'mode' => '{"heat":1,"cool":2,"auto":3,"dry":4,"fan":5}',
                'fan' => '{"auto":0,"silent":1,"1":2,"2":3,"3":4,"4":5}',
                'vdir' => '{"swing":1,"down":2,"mdown":3,"middle":4,"mup":5,"up":6}',
                'hdir' => '{"swing":1,"left":2,"mleft":3,"middle":4,"mright":5,"right":6,"soft":7}',
            ],
            [
                'name' => 'hs-3-mb-b',
                'device' => 'onokom-hs-3-mb-b',
                'temperature' => '{"min":16,"max":32}',
                'mode' => '{"heat":1,"cool":2,"auto":3,"dry":4,"fan":5}',
                'fan' => '{"auto":0,"silent":1,"1":2,"2":3,"3":4,"4":5}',
                'vdir' => '{"stop":0,"swing":1}',
                'hdir' => '{"stop":0,"swing":1}',
            ],
            [
                'name' => 'hr-1-mb-b',
                'device' => 'onokom-hr-1-mb-b',
                'temperature' => '{"min":16,"max":32}',
                'mode' => '{"heat":1,"cool":2,"auto":3,"dry":4,"fan":5}',
                'fan' => '{"auto":0,"silent":1,"1":2,"2":3,"3":4,"turbo":5}',
                'vdir' => '{"swing":1,"down":2,"2":3,"3":4,"middle":5,"5":6,"6":7,"up":8}',
                'hdir' => '{"swing":1,"left":2,"mleft":3,"middle":4,"mright":5,"right":6}',
            ],
            [
                'name' => 'hs-6-mb-b',
                'device' => 'onokom-hs-6-mb-b',
                'temperature' => '{"min":16,"max":30}',
                'mode' => '{"heat":1,"cool":2,"auto":3,"dry":4,"fan":5}',
                'fan' => '{"auto":0,"1":1,"2":2,"3":3}',
                'vdir' => '{"stop":0,"swing":1}',
                'hdir' => '{"stop":0,"swing":1}',
            ],
            [
                'name' => 'mh-8-mb-b',
                'device' => 'onokom-mh-8-mb-b',
                'temperature' => '{"min":16,"max":32}',
                'mode' => '{"heat":1,"cool":2,"auto":3,"dry":4,"fan":5}',
                'fan' => '{"auto":0,"1":1,"2":2,"3":3}',
                'vdir' => '{"swing":1,"down":2,"mdown":3,"mup":4,"up":5}',
                'hdir' => null,
            ],
        ];

        foreach ($conditionerTypes as $conditionerType) {
            $name = $conditionerType['name'];
            unset($conditionerType['name']);

            ConditionerType::updateOrCreate(
                ['name' => $name], $conditionerType
            );
        }
    }
}
